import { ActiveTrip, NetworkPrediction, AiFeature } from "./types";

export const ACTIVE_TRIPS: ActiveTrip[] = [
  {
    id: "trip-1042",
    orderId: "ORD-1042",
    driverName: "Sarah Lopez",
    driverType: "Company",
    vehicleId: "Tractor 28",
    status: "on-time",
    locationSummary: "I-94 near Milwaukee, WI",
    speedMph: 58,
    eta: "12:45 PM",
    etaConfidence: 0.84,
    stopsRemaining: 2,
    nextStop: "Madison, WI",
    exceptionAlerts: [],
    timeline: [
      { time: "06:10", label: "Departed Chicago Hub", type: "success" },
      { time: "07:35", label: "Cleared weigh station", type: "info" },
      { time: "09:15", label: "Passing Milwaukee", detail: "Running on schedule" },
    ],
    aiPrediction: "On pace to deliver 8 minutes early based on current traffic conditions.",
    route: {
      origin: "Chicago, IL",
      destination: "Minneapolis, MN",
      milesRemaining: 187,
      percentageComplete: 62,
    },
    position: { x: 62, y: 41 },
    trail: [
      { x: 15, y: 68 },
      { x: 28, y: 60 },
      { x: 44, y: 52 },
      { x: 62, y: 41 },
    ],
    contact: {
      driverPhone: "(312) 555-0178",
      dispatchChannel: "Dispatch Channel 3",
    },
  },
  {
    id: "trip-2090",
    orderId: "ORD-2090",
    driverName: "Marcus Hill",
    driverType: "Owner Operator",
    vehicleId: "Unit 1142",
    status: "at-risk",
    locationSummary: "I-80 outside Des Moines, IA",
    speedMph: 42,
    eta: "4:05 PM",
    etaConfidence: 0.58,
    stopsRemaining: 1,
    nextStop: "Council Bluffs, IA",
    exceptionAlerts: ["Thunderstorm warning ahead"],
    timeline: [
      { time: "05:45", label: "Departed Omaha Yard", type: "success" },
      { time: "09:20", label: "Weather alert issued", type: "alert", detail: "Heavy rain expected in 45 min" },
      { time: "09:55", label: "Reduced speed for weather", type: "alert" },
    ],
    aiPrediction: "Projected 18 minute delay unless alternate route via I-35 is taken.",
    route: {
      origin: "Omaha, NE",
      destination: "Chicago, IL",
      milesRemaining: 351,
      percentageComplete: 34,
    },
    position: { x: 44, y: 58 },
    trail: [
      { x: 10, y: 76 },
      { x: 22, y: 70 },
      { x: 32, y: 65 },
      { x: 44, y: 58 },
    ],
    contact: {
      driverPhone: "(531) 555-0126",
      dispatchChannel: "Ops Midwest",
    },
  },
  {
    id: "trip-3012",
    orderId: "ORD-3012",
    driverName: "Hannah Park",
    driverType: "Company",
    vehicleId: "Tractor 08",
    status: "delayed",
    locationSummary: "I-35 near Wichita, KS",
    speedMph: 36,
    eta: "3:20 PM",
    etaConfidence: 0.44,
    stopsRemaining: 3,
    nextStop: "Oklahoma City, OK",
    exceptionAlerts: ["Route deviation detected", "Delivery window at risk"],
    timeline: [
      { time: "04:55", label: "Left Kansas City DC", type: "success" },
      { time: "08:40", label: "Off-route detour", type: "alert", detail: "Construction closure on I-35" },
      { time: "09:05", label: "Rejoined planned route", type: "info" },
    ],
    aiPrediction: "Likely to arrive 30 minutes late; recommend notifying consignee.",
    route: {
      origin: "Kansas City, MO",
      destination: "Dallas, TX",
      milesRemaining: 298,
      percentageComplete: 41,
    },
    position: { x: 54, y: 72 },
    trail: [
      { x: 18, y: 30 },
      { x: 32, y: 40 },
      { x: 44, y: 54 },
      { x: 54, y: 72 },
    ],
    contact: {
      driverPhone: "(913) 555-0198",
      dispatchChannel: "South Central Pod",
    },
  },
  {
    id: "trip-4156",
    orderId: "ORD-4156",
    driverName: "Diego Ramirez",
    driverType: "Rental",
    vehicleId: "Rental-22",
    status: "on-time",
    locationSummary: "I-25 near Colorado Springs, CO",
    speedMph: 63,
    eta: "6:10 PM",
    etaConfidence: 0.79,
    stopsRemaining: 1,
    nextStop: "Pueblo, CO",
    exceptionAlerts: [],
    timeline: [
      { time: "07:05", label: "Departed Denver", type: "success" },
      { time: "08:45", label: "Cleared weigh station", type: "info" },
      { time: "09:30", label: "Passing Colorado Springs", detail: "Maintaining schedule" },
    ],
    aiPrediction: "No risk detected; trending 5 minutes early.",
    route: {
      origin: "Denver, CO",
      destination: "El Paso, TX",
      milesRemaining: 635,
      percentageComplete: 24,
    },
    position: { x: 18, y: 46 },
    trail: [
      { x: 12, y: 12 },
      { x: 14, y: 24 },
      { x: 16, y: 36 },
      { x: 18, y: 46 },
    ],
    contact: {
      driverPhone: "(720) 555-0143",
      dispatchChannel: "Mountain Ops",
    },
  },
  {
    id: "trip-5094",
    orderId: "ORD-5094",
    driverName: "Priya Desai",
    driverType: "Company",
    vehicleId: "Tractor 33",
    status: "on-time",
    locationSummary: "I-5 near Redding, CA",
    speedMph: 57,
    eta: "8:30 PM",
    etaConfidence: 0.9,
    stopsRemaining: 2,
    nextStop: "Sacramento, CA",
    exceptionAlerts: [],
    timeline: [
      { time: "06:25", label: "Departed Portland, OR", type: "success" },
      { time: "07:55", label: "Border crossing completed", type: "info" },
      { time: "09:45", label: "Entering Redding", detail: "Traffic flowing freely" },
    ],
    aiPrediction: "Expected to hit delivery window exactly on schedule.",
    route: {
      origin: "Portland, OR",
      destination: "Los Angeles, CA",
      milesRemaining: 567,
      percentageComplete: 38,
    },
    position: { x: 6, y: 22 },
    trail: [
      { x: 4, y: 6 },
      { x: 5, y: 12 },
      { x: 6, y: 18 },
      { x: 6, y: 22 },
    ],
    contact: {
      driverPhone: "(503) 555-0165",
      dispatchChannel: "West Coast Pod",
    },
  },
];

export const NETWORK_PREDICTION: NetworkPrediction = {
  expectedCompletion: "4:18 PM CT",
  confidence: 0.78,
  narrative: "Majority of trips trending on-time; watching storms forming along I-80 and construction on I-35.",
  trendingRisk: "Weather band tracking east across Des Moines corridor in next 45 minutes.",
};

export const AI_FEATURES: AiFeature[] = [
  {
    id: "eta",
    emoji: "🕒",
    label: "ETA Prediction",
    description: "ML-adjusted ETAs blend traffic, weather, and driver behavior for each lane.",
  },
  {
    id: "deviation",
    emoji: "⚠️",
    label: "Route Deviation Alerts",
    description: "Detects off-route miles in under 2 minutes and flags necessary interventions.",
  },
  {
    id: "delivery",
    emoji: "📦",
    label: "Delivery Prediction",
    description: "Highlights shipments likely to miss their window with recommended responses.",
  },
  {
    id: "routing",
    emoji: "🧭",
    label: "Optimal Routing",
    description: "Suggests proactive re-routes using live incident and dwell data.",
  },
];
