import { Driver, Unit } from "./types";

export const mockDrivers: Driver[] = [
  {
    id: "D001",
    name: "Jeff Churchill",
    type: "COM",
    status: "available",
    location: "Guelph, ON",
    unitId: "U001",
    stats: {
      totalTrips: 128,
      onTimePercentage: 98,
      avgMargin: 18.5,
    },
    aiScore: 95,
    avatar: "/avatars/driver-1.jpg",
    profile: {
      license: "AZ-123456",
      licenseExpiration: "2026-12-31",
      certifications: ["Hazmat", "Tanker"],
      emergencyContact: "Jane Doe (555) 123-4567",
      payStructure: "$0.65/mile",
    },
    hos: {
      driveTimeRemaining: "8h 15m",
      cycleTimeRemaining: "55h 30m",
      predictedViolation: null,
    },
    performance: {
      weeklyRevenue: 4500,
      cpm: 2.15,
      fuelEfficiency: 6.8,
    },
    tripHistory: [],
    documents: [],
  },
  {
    id: "D002",
    name: "Denise Starr",
    type: "RNR",
    status: "on-trip",
    location: "Windsor, ON",
    unitId: "U002",
    stats: {
      totalTrips: 95,
      onTimePercentage: 99,
      avgMargin: 21.2,
    },
    aiScore: 98,
    avatar: "/avatars/driver-2.jpg",
    profile: {
        license: "AZ-654321",
        licenseExpiration: "2025-10-20",
        certifications: ["Doubles/Triples"],
        emergencyContact: "John Smith (555) 987-6543",
        payStructure: "25% of revenue",
      },
      currentTrip: {
        tripId: "T-789",
        destination: "Chicago, IL",
        hosRemaining: "4h 30m",
        nextAction: "Deliver at 3:00 PM",
      },
      hos: {
        driveTimeRemaining: "4h 30m",
        cycleTimeRemaining: "32h 10m",
        predictedViolation: "Potential violation in 48h",
      },
      performance: {
        weeklyRevenue: 5200,
        cpm: 1.98,
        fuelEfficiency: 7.2,
      },
      tripHistory: [],
      documents: [],
  },
  {
    id: "D003",
    name: "Gurdip Dhanal",
    type: "OO",
    status: "off-duty",
    location: "Brampton, ON",
    unitId: "U003",
    stats: {
      totalTrips: 210,
      onTimePercentage: 95,
      avgMargin: 15.1,
    },
    aiScore: 91,
    avatar: "/avatars/driver-3.jpg",
    profile: {
        license: "AZ-789012",
        licenseExpiration: "2027-05-15",
        certifications: [],
        emergencyContact: "Priya Dhanal (555) 111-2222",
        payStructure: "80% of revenue",
      },
      hos: {
        driveTimeRemaining: "11h 00m",
        cycleTimeRemaining: "70h 00m",
        predictedViolation: null,
      },
      performance: {
        weeklyRevenue: 6800,
        cpm: 2.55,
        fuelEfficiency: 6.2,
      },
      tripHistory: [],
      documents: [],
  },
];

export const mockUnits: Unit[] = [
    {
      id: "U001",
      make: "Freightliner",
      model: "Cascadia",
      year: 2022,
      status: "active",
      driverId: "D001",
      driverName: "Jeff Churchill",
      location: "Guelph, ON",
      mileage: 150000,
      lastService: "2025-10-15",
      aiMaintenancePredictor: "Brake service recommended in 3,500 miles",
      overview: {
        vin: "1FUJGHF88NKL12345",
        licensePlate: "AZ12 345",
        capacity: "80,000 lbs",
        ownership: "owned",
      },
      maintenance: {
        nextService: "2026-01-15",
        history: [],
      },
      costs: {
        weeklyFixed: 500,
        cpm: 0.85,
      },
      telematics: {
        fuelEfficiency: 6.8,
        idleTime: 15,
        hardBrakingEvents: 2,
        speedViolations: 1,
      },
    },
    {
      id: "U002",
      make: "Volvo",
      model: "VNL 860",
      year: 2023,
      status: "active",
      driverId: "D002",
      driverName: "Denise Starr",
      location: "Windsor, ON",
      mileage: 85000,
      lastService: "2025-09-20",
      aiMaintenancePredictor: "Tire rotation due in 1,200 miles",
      overview: {
        vin: "4V4NC9TH0PBN54321",
        licensePlate: "BY34 567",
        capacity: "80,000 lbs",
        ownership: "leased",
      },
      maintenance: {
        nextService: "2025-12-20",
        history: [],
      },
      costs: {
        weeklyFixed: 650,
        cpm: 0.78,
      },
      telematics: {
        fuelEfficiency: 7.2,
        idleTime: 12,
        hardBrakingEvents: 1,
        speedViolations: 0,
      },
    },
    {
        id: "U003",
        make: "Peterbilt",
        model: "579",
        year: 2021,
        status: "maintenance",
        driverId: "D003",
        driverName: "Gurdip Dhanal",
        location: "Brampton, ON",
        mileage: 250000,
        lastService: "2025-11-01",
        aiMaintenancePredictor: "Engine diagnostics show potential injector issue.",
        overview: {
          vin: "1XP-HD49X-7-CD12345",
          licensePlate: "CV56 789",
          capacity: "80,000 lbs",
          ownership: "oo",
        },
        maintenance: {
          nextService: "2026-02-01",
          history: [],
        },
        costs: {
          weeklyFixed: 300,
          cpm: 1.1,
        },
        telematics: {
          fuelEfficiency: 6.2,
          idleTime: 22,
          hardBrakingEvents: 5,
          speedViolations: 3,
        },
      },
  ];
  