import { DispatchOrder, Driver, AIRecommendation } from "./types";

export const MOCK_DISPATCH_ORDERS: DispatchOrder[] = [
  // Unassigned (3)
  {
    id: "ORD-1001",
    customer: "Walmart Logistics",
    origin: { city: "Toronto", state: "ON" },
    destination: { city: "Detroit", state: "MI" },
    pickupTime: "2025-11-09T14:00:00Z",
    deliveryTime: "2025-11-10T08:00:00Z",
    status: "unassigned",
    priority: "high",
    aiMatchScore: 87,
    miles: 236,
    estCost: 890,
    revenue: 1120,
    margin: 0.205,
  },
  {
    id: "ORD-1002",
    customer: "Target Distribution",
    origin: { city: "Hamilton", state: "ON" },
    destination: { city: "Buffalo", state: "NY" },
    pickupTime: "2025-11-09T16:00:00Z",
    deliveryTime: "2025-11-10T10:00:00Z",
    status: "unassigned",
    priority: "medium",
    aiMatchScore: 72,
    miles: 142,
    estCost: 623,
    revenue: 785,
    margin: 0.206,
  },
  {
    id: "ORD-1003",
    customer: "Home Depot Supply",
    origin: { city: "London", state: "ON" },
    destination: { city: "Cleveland", state: "OH" },
    pickupTime: "2025-11-10T08:00:00Z",
    deliveryTime: "2025-11-11T06:00:00Z",
    status: "unassigned",
    priority: "low",
    aiMatchScore: 65,
    miles: 287,
    estCost: 1034,
    revenue: 1250,
    margin: 0.173,
  },
  
  // Assigned (2)
  {
    id: "ORD-1004",
    customer: "Costco Wholesale",
    origin: { city: "Guelph", state: "ON" },
    destination: { city: "Erie", state: "PA" },
    pickupTime: "2025-11-09T18:00:00Z",
    deliveryTime: "2025-11-10T12:00:00Z",
    status: "assigned",
    driver: { id: "DRV-001", name: "Mike Anderson", initials: "MA" },
    priority: "medium",
    miles: 198,
    estCost: 756,
    revenue: 980,
    margin: 0.229,
  },
  {
    id: "ORD-1005",
    customer: "IKEA Distribution",
    origin: { city: "Mississauga", state: "ON" },
    destination: { city: "Pittsburgh", state: "PA" },
    pickupTime: "2025-11-10T06:00:00Z",
    deliveryTime: "2025-11-11T14:00:00Z",
    status: "assigned",
    driver: { id: "DRV-002", name: "Sarah Chen", initials: "SC" },
    priority: "high",
    miles: 312,
    estCost: 1178,
    revenue: 1540,
    margin: 0.235,
  },
  
  // En Route to Pickup (1)
  {
    id: "ORD-1006",
    customer: "Amazon Freight",
    origin: { city: "Brampton", state: "ON" },
    destination: { city: "Rochester", state: "NY" },
    pickupTime: "2025-11-09T10:00:00Z",
    deliveryTime: "2025-11-09T20:00:00Z",
    status: "en_route_pickup",
    driver: { id: "DRV-003", name: "James Wilson", initials: "JW" },
    priority: "high",
    eta: "2025-11-09T09:45:00Z",
    distanceRemaining: 12,
    miles: 178,
    estCost: 689,
    revenue: 890,
    margin: 0.226,
  },
  
  // At Pickup (2)
  {
    id: "ORD-1007",
    customer: "Best Buy Logistics",
    origin: { city: "Oakville", state: "ON" },
    destination: { city: "Syracuse", state: "NY" },
    pickupTime: "2025-11-09T08:00:00Z",
    deliveryTime: "2025-11-09T18:00:00Z",
    status: "at_pickup",
    driver: { id: "DRV-004", name: "Emily Rodriguez", initials: "ER" },
    priority: "medium",
    dwellTime: 23, // minutes
    miles: 203,
    estCost: 778,
    revenue: 995,
    margin: 0.218,
  },
  {
    id: "ORD-1008",
    customer: "Lowe's Logistics",
    origin: { city: "Kitchener", state: "ON" },
    destination: { city: "Columbus", state: "OH" },
    pickupTime: "2025-11-09T09:30:00Z",
    deliveryTime: "2025-11-10T08:00:00Z",
    status: "at_pickup",
    driver: { id: "DRV-005", name: "Paul Jessome", initials: "PJ" },
    priority: "low",
    dwellTime: 45,
    miles: 312,
    estCost: 1189,
    revenue: 1450,
    margin: 0.180,
  },
  
  // In Transit (3)
  {
    id: "ORD-1009",
    customer: "FedEx Ground",
    origin: { city: "Windsor", state: "ON" },
    destination: { city: "Indianapolis", state: "IN" },
    pickupTime: "2025-11-09T06:00:00Z",
    deliveryTime: "2025-11-09T20:00:00Z",
    status: "in_transit",
    driver: { id: "DRV-006", name: "David Kim", initials: "DK" },
    priority: "high",
    eta: "2025-11-09T19:30:00Z",
    progressPct: 67,
    hosRemaining: 5.2,
    miles: 398,
    estCost: 1489,
    revenue: 1890,
    margin: 0.212,
  },
  {
    id: "ORD-1010",
    customer: "UPS Freight",
    origin: { city: "Cambridge", state: "ON" },
    destination: { city: "Toledo", state: "OH" },
    pickupTime: "2025-11-09T07:00:00Z",
    deliveryTime: "2025-11-09T16:00:00Z",
    status: "in_transit",
    driver: { id: "DRV-007", name: "Lisa Zhang", initials: "LZ" },
    priority: "medium",
    eta: "2025-11-09T15:45:00Z",
    progressPct: 82,
    hosRemaining: 3.8,
    miles: 189,
    estCost: 723,
    revenue: 910,
    margin: 0.205,
  },
  {
    id: "ORD-1011",
    customer: "Sysco Foods",
    origin: { city: "Burlington", state: "ON" },
    destination: { city: "Grand Rapids", state: "MI" },
    pickupTime: "2025-11-09T05:00:00Z",
    deliveryTime: "2025-11-09T14:00:00Z",
    status: "in_transit",
    driver: { id: "DRV-008", name: "Robert Taylor", initials: "RT" },
    priority: "high",
    eta: "2025-11-09T13:20:00Z",
    progressPct: 88,
    hosRemaining: 2.1,
    miles: 267,
    estCost: 1012,
    revenue: 1320,
    margin: 0.233,
  },
  
  // At Delivery (1)
  {
    id: "ORD-1012",
    customer: "Pepsi Distribution",
    origin: { city: "Vaughan", state: "ON" },
    destination: { city: "Flint", state: "MI" },
    pickupTime: "2025-11-09T06:30:00Z",
    deliveryTime: "2025-11-09T13:00:00Z",
    status: "at_delivery",
    driver: { id: "DRV-009", name: "Maria Garcia", initials: "MG" },
    priority: "medium",
    dwellTime: 18,
    miles: 223,
    estCost: 845,
    revenue: 1075,
    margin: 0.214,
  },
  
  // Completed (2)
  {
    id: "ORD-1013",
    customer: "Coca-Cola",
    origin: { city: "Markham", state: "ON" },
    destination: { city: "Lansing", state: "MI" },
    pickupTime: "2025-11-09T04:00:00Z",
    deliveryTime: "2025-11-09T11:00:00Z",
    status: "completed",
    driver: { id: "DRV-010", name: "John Martinez", initials: "JM" },
    priority: "low",
    miles: 289,
    estCost: 1098,
    revenue: 1450,
    margin: 0.243,
  },
  {
    id: "ORD-1014",
    customer: "Nestle Foods",
    origin: { city: "Richmond Hill", state: "ON" },
    destination: { city: "Ann Arbor", state: "MI" },
    pickupTime: "2025-11-09T05:30:00Z",
    deliveryTime: "2025-11-09T12:00:00Z",
    status: "completed",
    driver: { id: "DRV-011", name: "Amanda White", initials: "AW" },
    priority: "medium",
    miles: 256,
    estCost: 967,
    revenue: 1180,
    margin: 0.180,
  },
];

export const MOCK_DRIVERS: Driver[] = [
  {
    id: "DRV-001",
    name: "Mike Anderson",
    initials: "MA",
    type: "company",
    status: "on_trip",
    currentLocation: "Guelph, ON",
    hosRemaining: 8.5,
    assignedUnit: "T-1045",
    currentOrderId: "ORD-1004",
    aiEfficiencyScore: 92,
  },
  {
    id: "DRV-002",
    name: "Sarah Chen",
    initials: "SC",
    type: "company",
    status: "on_trip",
    currentLocation: "Mississauga, ON",
    hosRemaining: 11.0,
    assignedUnit: "T-1052",
    currentOrderId: "ORD-1005",
    aiEfficiencyScore: 88,
  },
  {
    id: "DRV-003",
    name: "James Wilson",
    initials: "JW",
    type: "rental",
    status: "on_trip",
    currentLocation: "Brampton, ON",
    hosRemaining: 9.2,
    assignedUnit: "R-3421",
    currentOrderId: "ORD-1006",
    aiEfficiencyScore: 85,
  },
  {
    id: "DRV-004",
    name: "Emily Rodriguez",
    initials: "ER",
    type: "company",
    status: "on_trip",
    currentLocation: "Oakville, ON",
    hosRemaining: 10.3,
    assignedUnit: "T-1067",
    currentOrderId: "ORD-1007",
    aiEfficiencyScore: 94,
  },
  {
    id: "DRV-005",
    name: "Paul Jessome",
    initials: "PJ",
    type: "owner_operator",
    status: "on_trip",
    currentLocation: "Kitchener, ON",
    hosRemaining: 7.8,
    assignedUnit: "O-5678",
    currentOrderId: "ORD-1008",
    aiEfficiencyScore: 78,
  },
  {
    id: "DRV-006",
    name: "David Kim",
    initials: "DK",
    type: "company",
    status: "on_trip",
    currentLocation: "Near Toledo, OH",
    hosRemaining: 5.2,
    assignedUnit: "T-1089",
    currentOrderId: "ORD-1009",
    aiEfficiencyScore: 91,
  },
  {
    id: "DRV-007",
    name: "Lisa Zhang",
    initials: "LZ",
    type: "rental",
    status: "on_trip",
    currentLocation: "Near Toledo, OH",
    hosRemaining: 3.8,
    assignedUnit: "R-3445",
    currentOrderId: "ORD-1010",
    aiEfficiencyScore: 86,
  },
  {
    id: "DRV-008",
    name: "Robert Taylor",
    initials: "RT",
    type: "company",
    status: "on_trip",
    currentLocation: "Near Grand Rapids, MI",
    hosRemaining: 2.1,
    assignedUnit: "T-1098",
    currentOrderId: "ORD-1011",
    aiEfficiencyScore: 89,
  },
  {
    id: "DRV-009",
    name: "Maria Garcia",
    initials: "MG",
    type: "owner_operator",
    status: "on_trip",
    currentLocation: "Flint, MI",
    hosRemaining: 4.5,
    assignedUnit: "O-5701",
    currentOrderId: "ORD-1012",
    aiEfficiencyScore: 83,
  },
  {
    id: "DRV-010",
    name: "John Martinez",
    initials: "JM",
    type: "company",
    status: "available",
    currentLocation: "Lansing, MI",
    hosRemaining: 11.0,
    assignedUnit: "T-1112",
    nextAvailable: "2025-11-09T12:00:00Z",
    aiEfficiencyScore: 87,
  },
  {
    id: "DRV-011",
    name: "Amanda White",
    initials: "AW",
    type: "rental",
    status: "available",
    currentLocation: "Ann Arbor, MI",
    hosRemaining: 10.5,
    assignedUnit: "R-3489",
    nextAvailable: "2025-11-09T13:00:00Z",
    aiEfficiencyScore: 90,
  },
  {
    id: "DRV-012",
    name: "Carlos Rivera",
    initials: "CR",
    type: "company",
    status: "available",
    currentLocation: "Toronto, ON",
    hosRemaining: 11.0,
    assignedUnit: "T-1125",
    aiEfficiencyScore: 84,
  },
  {
    id: "DRV-013",
    name: "Jennifer Lee",
    initials: "JL",
    type: "owner_operator",
    status: "hos_break",
    currentLocation: "Hamilton, ON",
    hosRemaining: 0.5,
    assignedUnit: "O-5734",
    nextAvailable: "2025-11-09T11:30:00Z",
    aiEfficiencyScore: 92,
  },
  {
    id: "DRV-014",
    name: "Thomas Brown",
    initials: "TB",
    type: "company",
    status: "off_duty",
    currentLocation: "Guelph, ON",
    hosRemaining: 11.0,
    assignedUnit: "T-1134",
    nextAvailable: "2025-11-10T06:00:00Z",
    aiEfficiencyScore: 81,
  },
];

export const MOCK_AI_RECOMMENDATIONS: AIRecommendation[] = [
  {
    id: "REC-001",
    type: "assignment",
    orderId: "ORD-1001",
    driverId: "DRV-012",
    reason: "Carlos Rivera is in Toronto with 11 hours HOS. Direct route, 15% cost savings vs rental driver.",
    costSavings: 134,
    confidence: 92,
  },
  {
    id: "REC-002",
    type: "assignment",
    orderId: "ORD-1002",
    driverId: "DRV-013",
    reason: "Jennifer Lee finishing HOS break in 30 minutes in Hamilton. Shortest distance to pickup.",
    etaImprovement: -0.5,
    confidence: 88,
  },
  {
    id: "REC-003",
    type: "conflict",
    orderId: "ORD-1009",
    driverId: "DRV-006",
    reason: "David Kim has only 5.2 hours HOS remaining. May violate 70-hour rule before delivery. Suggest reassignment.",
    confidence: 85,
  },
];
