export const queryKeys = {
  dashboard: ["dashboard"] as const,
  analytics: ["analytics"] as const,
  orders: () => ["orders"] as const,
  order: (id: string) => ["orders", id] as const,
  dispatch: ["dispatch"] as const,
  trips: (filters?: { status?: string }) => ["trips", filters] as const,
  trip: (id: string) => ["trips", id] as const,
  costing: ["costing"] as const,
  search: (query: string) => ["search", query] as const,
  masterData: {
    drivers: ["master-data", "drivers"] as const,
    units: ["master-data", "units"] as const,
    rules: ["master-data", "rules"] as const,
    events: ["master-data", "events"] as const,
  },
  admin: {
    drivers: ["admin", "drivers"] as const,
    units: ["admin", "units"] as const,
    rules: ["admin", "rules"] as const,
    events: ["admin", "events"] as const,
    lanes: ["admin", "lanes"] as const,
    orders: ["admin", "orders"] as const,
    trips: ["admin", "trips"] as const,
    customers: ["admin", "customers"] as const,
  },
  map: ["map-plan"] as const,
  customs: () => ["customs"] as const,
  customsDetail: (id: string) => ["customs", id] as const,
};

