import { NextResponse } from "next/server";

const orders = [
  {
    id: "ORD-10452",
    reference: "XPO-4452",
    customer: "Apex Manufacturing",
    pickup: "Dallas, TX",
    delivery: "Atlanta, GA",
    window: "05:00-09:00",
    status: "In Transit",
    ageHours: 18,
    cost: 1825,
    lane: "DAL → ATL",
  },
  {
    id: "ORD-10453",
    reference: "BN-2140",
    customer: "Brightline Retail",
    pickup: "Ontario, CA",
    delivery: "Denver, CO",
    window: "07:00-11:00",
    status: "At Risk",
    ageHours: 27,
    cost: 2410,
    lane: "ONT → DEN",
  },
  {
    id: "ORD-10454",
    reference: "NW-8821",
    customer: "Northwind",
    pickup: "Chicago, IL",
    delivery: "Kansas City, MO",
    window: "12:00-16:00",
    status: "Planning",
    ageHours: 5,
    lane: "ORD → MCI",
  },
  {
    id: "ORD-10455",
    reference: "ST-2219",
    customer: "Summit Tech",
    pickup: "Seattle, WA",
    delivery: "Reno, NV",
    window: "06:00-12:00",
    status: "In Transit",
    ageHours: 31,
    cost: 2655,
    lane: "SEA → RNO",
  },
  {
    id: "ORD-10456",
    reference: "ACM-9902",
    customer: "Acme Components",
    pickup: "Memphis, TN",
    delivery: "Charlotte, NC",
    window: "08:00-14:00",
    status: "New",
    ageHours: 3,
    lane: "MEM → CLT",
  },
  {
    id: "ORD-10457",
    reference: "BR-1129",
    customer: "Brightline Retail",
    pickup: "Phoenix, AZ",
    delivery: "Las Vegas, NV",
    window: "04:00-08:00",
    status: "Exception",
    ageHours: 42,
    cost: 1310,
    lane: "PHX → LAS",
  },
  {
    id: "ORD-10458",
    reference: "NW-8890",
    customer: "Northwind",
    pickup: "Columbus, OH",
    delivery: "Detroit, MI",
    window: "09:00-13:00",
    status: "Delivered",
    ageHours: 6,
    cost: 970,
    lane: "CMH → DTW",
  },
  {
    id: "ORD-10459",
    reference: "APX-6712",
    customer: "Apex Manufacturing",
    pickup: "Houston, TX",
    delivery: "Charlotte, NC",
    window: "02:00-06:00",
    status: "In Transit",
    ageHours: 21,
    cost: 2050,
    lane: "HOU → CLT",
  },
];

export async function GET() {
  return NextResponse.json({
    stats: {
      total: orders.length,
      new: orders.filter((order) => order.status === "New").length,
      inProgress: orders.filter((order) => ["Planning", "In Transit"].includes(order.status)).length,
      delayed: orders.filter((order) => ["At Risk", "Exception"].includes(order.status)).length,
    },
    filters: {
      customers: ["All", "Apex Manufacturing", "Brightline Retail", "Northwind", "Summit Tech", "Acme Components"],
      statuses: ["New", "Planning", "In Transit", "At Risk", "Delivered", "Exception"],
      lanes: ["DAL → ATL", "ONT → DEN", "ORD → MCI", "SEA → RNO", "MEM → CLT", "PHX → LAS", "CMH → DTW", "HOU → CLT"],
      dateRanges: ["Today", "48 Hours", "7 Days"],
    },
    data: orders,
  });
}
